language: node_js

node_js:
  - "4.1"
  - "4.0"

sudo: false
cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

script: "make test-travis"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

notifications:
  email:
    on_success: change
    on_failure: always
